from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))


def load_features(index_csv: Path) -> tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    df = pd.read_csv(index_csv)

    feats = [np.load(Path(p)) for p in df["feature_path"].tolist()]
    X = np.stack(feats).astype(np.float64)
    y = df["label"].to_numpy(dtype=np.int64)
    return X, y, df


def filter_dataframe(
    df: pd.DataFrame,
    split: str | None,
    label_name: str | None,
) -> pd.DataFrame:
    out = df
    if split is not None:
        out = out[out["split"] == split]
    if label_name is not None:
        out = out[out["label_name"] == label_name]
    return out.reset_index(drop=True)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Load saved deep features (.npy) and optionally pack them into one .npz file."
    )
    parser.add_argument(
        "--index-csv",
        type=Path,
        required=True,
        help="Path to features_index.csv generated by extract_best_model_features.py",
    )
    parser.add_argument(
        "--split", type=str, default=None, help="Split filter: train/valid/test"
    )
    parser.add_argument(
        "--label-name", type=str, default=None, help="Class filter, e.g. drone"
    )
    parser.add_argument(
        "--save-npz",
        type=Path,
        default=None,
        help="Optional path to save a single .npz file with X, y and metadata.",
    )

    args = parser.parse_args()

    _, _, df = load_features(args.index_csv)
    df = filter_dataframe(df, split=args.split, label_name=args.label_name)

    feats = [np.load(Path(p)) for p in df["feature_path"].tolist()]
    X = np.stack(feats).astype(np.float64)
    y = df["label"].to_numpy(dtype=np.int64)

    meta = {
        "n_samples": int(X.shape[0]),
        "feature_dim": int(X.shape[1]),
        "n_classes": int(len(np.unique(y))),
        "splits": sorted(df["split"].unique().tolist()),
        "classes": sorted(df["label_name"].unique().tolist()),
    }
    print(meta)

    if args.save_npz is not None:
        args.save_npz.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(
            args.save_npz,
            X=X,
            y=y,
            split=df["split"].to_numpy(),
            label_name=df["label_name"].to_numpy(),
            annotation_id=df["annotation_id"].to_numpy(),
            feature_path=df["feature_path"].to_numpy(),
        )
        print(f"Saved feature package: {args.save_npz}")

    print(f"Loaded X shape={X.shape}, y shape={y.shape}")


if __name__ == "__main__":
    main()
